// ROUND NAMES TYPES
export interface ROUND_NAMES_TYPE {
  START: 'START';
  PREFLOP: 'PREFLOP';
  FLOP: 'FLOP';
  TURN: 'TURN';
  RIVER: 'RIVER';
}

export const ROUND_NAMES: ROUND_NAMES_TYPE = {
  START: 'START',
  PREFLOP: 'PREFLOP',
  FLOP: 'FLOP',
  TURN: 'TURN',
  RIVER: 'RIVER',
};

// ACTION STATUS TYPES
export enum ACTION_STATUS_ENUM {
  CALL,
  ALL_IN,
  CHECK,
  BET,
  RAISE,
  FOLD,
  SMALL_BLIND,
  BIG_BLIND,
}

export const ACTION_STATUS_LABEL = {
  CALL: 'C',
  ALL_IN: 'A',
  CHECK: 'X',
  BET: 'B',
  RAISE: 'R',
  FOLD: 'F',
  SMALL_BLIND: 'SB',
  BIG_BLIND: 'BB',
};

export const ACTION_STATUS_CODE = {
  CALL: ACTION_STATUS_ENUM.CALL,
  ALL_IN: ACTION_STATUS_ENUM.ALL_IN,
  CHECK: ACTION_STATUS_ENUM.CHECK,
  BET: ACTION_STATUS_ENUM.BET,
  RAISE: ACTION_STATUS_ENUM.RAISE,
  FOLD: ACTION_STATUS_ENUM.FOLD,
  SMALL_BLIND: ACTION_STATUS_ENUM.SMALL_BLIND,
  BIG_BLIND: ACTION_STATUS_ENUM.BIG_BLIND,
};

// SLOT TYPES
export enum SLOT_TYPE_ENUM {
  NONE,
  SB,
  BB,
  UTG,
  UTG1,
  MP,
  MP2,
  HJ,
  CO,
  D,
}

export const SLOT_TYPE_LABEL = {
  NONE: 'VIEWER',
  SB: 'SB',
  BB: 'BB',
  UTG: 'UTG',
  UTG1: 'UTG+1',
  MP: 'MP',
  MP2: 'MP+1',
  HJ: 'HJ',
  CO: 'CO',
  D: 'D',
};

export const SLOT_TYPE_WITH_INDEX = {
  0: 'NONE',
  1: 'SB',
  2: 'BB',
  3: 'UTG',
  4: 'UTG+1',
  5: 'MP',
  6: 'MP+1',
  7: 'HJ',
  8: 'CO',
  9: 'D',
};

export const SLOT_TYPE_CODE = {
  NONE: SLOT_TYPE_ENUM.NONE,
  SB: SLOT_TYPE_ENUM.SB,
  BB: SLOT_TYPE_ENUM.BB,
  UTG: SLOT_TYPE_ENUM.UTG,
  UTG1: SLOT_TYPE_ENUM.UTG1,
  MP: SLOT_TYPE_ENUM.MP,
  MP2: SLOT_TYPE_ENUM.MP2,
  HJ: SLOT_TYPE_ENUM.HJ,
  CO: SLOT_TYPE_ENUM.CO,
  D: SLOT_TYPE_ENUM.D,
};

// HAND HTTP STATUS CODE
export const STATUS_HAND_HTTP_CODE = {
  SUCCESS: 200,
  CREATED: 201,
  INVALID_PARAM: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  HAND_NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
};
